Js syntax
antoniaat/JS-Advanced-Sep-2023 pull request #11
Opened 2023-09-23 19:22 UTC by lsfckt

2023-09-24 16:35 UTC, georgi-georgiev95 approved these changes

2023-09-24 17:57 UTC, antoniaat requested changes

2023-09-24 17:57 UTC, antoniaat commented on 01-js-syntax/exercise/02-greatest-common-divisor.js
> +    if (second === 0) {
Why not deleting this empty file and trying to make the function shorter with ternary operator?
IMO it will look better.

2023-09-24 17:57 UTC, antoniaat requested changes

2023-09-24 17:57 UTC, antoniaat commented on 01-js-syntax/lab/01-echo-function.js
> +
I don't think this solution needs a lot of reviews so I suggest deleting this file.

2023-09-25 08:15 UTC, georgi-georgiev95 approved these changes

2023-09-25 08:15 UTC, georgi-georgiev95 approved these changes

2023-09-25 15:56 UTC, antoniaat approved these changes

2023-09-25 15:56 UTC, merged