DOM-02-PascalCamel-Solution
antoniaat/JS-Advanced-Sep-2023 pull request #18
Opened 2023-09-25 19:31 UTC by fabriciovd

Because of Judge, I must nest the convertText function in order to use it. Don't like it like that.

2023-09-25 20:18 UTC, zlatozaraZlatkova commented
I tried to make your code more efficient by reducing the number of repeats. You can see the file called Update solution.js.

2023-09-25 21:45 UTC, fabriciovd commented
Good one.

2023-09-26 06:22 UTC, Daooobg requested changes
You can use const instead of let

2023-09-26 07:56 UTC, Daooobg approved these changes

2023-09-27 08:20 UTC, Daooobg approved these changes

2023-09-29 17:33 UTC, georgi-georgiev95 approved these changes

2023-09-29 17:33 UTC, merged