02. Time-Converter
antoniaat/JS-Advanced-Sep-2023 pull request #21
Opened 2023-10-01 10:39 UTC by MilenaGeorgieva95

02. Time-Converter

2023-10-03 08:02 UTC, georgi-georgiev95 reviewed
Adding the event listener to the main container makes the code difficult to read. U can use querrySelectorAll('button') and then parse it to an Array and using forEach u can add events to the buttons.

2023-10-05 06:16 UTC, MilenaGeorgieva95 commented
Thank you! I have done it like that also, it says in the task description to do it that way. Just wanted to try another option to see if it works. Just wanted to say also-I am your big fan from the lectures, your code is always on point😁

2023-10-05 09:40 UTC, antoniaat requested changes

2023-10-05 09:40 UTC, antoniaat commented on 05-dom-events/exercise/02. Time-Converter/solution.js
> +  function attachEventsListeners() {
Why these functions have the same name?

2023-10-05 09:40 UTC, antoniaat commented on 05-dom-events/exercise/02. Time-Converter/solution.js
> +    let main = document.querySelector("main");
Consider declaring variables that you are not going to change with const

2023-10-05 09:40 UTC, antoniaat commented on 05-dom-events/exercise/02. Time-Converter/solution.js
> +        return {
You can try to omit the return statement with one idea shorter syntax:

 days: (num) => ({
          days: num,
          hours: num * 24,
          minutes: num * 1440,
          seconds: num * 86400, 
}),

2023-10-05 13:54 UTC, closed without merging