feat: number convertor
antoniaat/JS-Advanced-Sep-2023 pull request #8
Opened 2023-09-22 17:15 UTC by Daooobg

This is what i did

2023-09-24 18:04 UTC, antoniaat requested changes
The branch should point to main - please rebase.

2023-09-24 18:04 UTC, antoniaat commented on 04-dom/exercise/09-numberConvertor.js
> +    let optionBinary = document.createElement("OPTION");
Why not using `const` here as well?

2023-09-24 18:04 UTC, antoniaat commented on 04-dom/exercise/09-numberConvertor.js
> +    let optionBinary = document.createElement("OPTION");
+When we are creating or taking an element reference I suggest to always put name in the end so to remember that inside we have live DOM element.

2023-09-24 18:04 UTC, antoniaat commented on 04-dom/exercise/09-numberConvertor.js
> +    btn[0].onclick = function () {
What is btn[0]? I suggest creating a variable with descriptive name for this.

2023-09-24 18:04 UTC, antoniaat commented on 04-dom/exercise/09-numberConvertor.js
> +    function convertToHeXadecimal(num) {
Of course this function works fine but if you have the wish you can research for some ways to improve it. I would suggest something like this (not tested, just a suggestion):

```javascript
function convertToHexadecimal(num) {
  // Base case: if num is 0, return '0' (special case)
  if (num === 0) return '0';

  // Define a string containing all hexadecimal characters in order
  const hexChars = '0123456789ABCDEF';

  // Initialize an empty string for the result
  let result = '';

  // Loop until num becomes 0
  while (num > 0) {
    // Calculate the remainder when dividing by 16 (hexadecimal base)
    const digit = num % 16;

    // Prepend the corresponding hexadecimal character to the result
    result = hexChars[digit] + result;

    // Reduce num by the integer division by 16
    num = Math.floor(num / 16);
  }

  // Return the hexadecimal representation of the original number
  return result;
}
```

2023-09-25 15:57 UTC, antoniaat approved these changes
Looks much better! Great job!

2023-09-27 08:24 UTC, zlatozaraZlatkova approved these changes

2023-09-27 08:26 UTC, merged